### ISSUE TITLE
Potential Auth break with PasswordField

### ISSUE THREAD

**Issue by Ghosts** [Ghosts/JavaFX_Login_Dialog#2]
Changed TextField to PasswordField for the passwords, unsure what effects it may have.

If it's all good I'll close.

**Comment by doughepi** [comment]
Was planning on doing that eventually, just makes it easier to debug when you can see what you're typing :) It shouldn't have any effect on the actual runtime.

**Comment by Ghosts** [comment]
Sweetness 👌
